const Data = [
  {
    id: 1,
    img: "public/Images/d.jpg",
    name: "Manoj kumar panda",
    stream: "BCA",
    description: "Mern stack developer",
    facebook: "https://www.facebook.com/loaferdjboy.papu",
    instagram: "https://www.instagram.com/oniii_chan_69_/",
    twitter: "https://www.twitter.com/",
    youtube: "https://www.youtube.com/",
    linkedin: "https://www.linkedin.com/",
    skills: [
      "HTML",
      "CSS",
      "javascript",
      "React",
      "Django",
      "Flask",
      "Python",
      "Java",
      "MySQL",
      "Mongodb",
      "Dockor",
      "NodeJS",
    ],
  },
  {
    id: 2,
    img: "images/r.jpg",
    name: "Rakesh kumar parida",
    stream: "MCA",
    description: "Full-stack Developer",
    facebook: "https://www.facebook.com/jstarkumar.rakesh",
    instagram: "https://www.instagram.com/mr_r.a.k.e.s.h/",
    twitter: "https://www.twitter.com/",
    youtube: "https://www.youtube.com/",
    linkedin: "https://www.linkedin.com/",
    skills: ["HTML", "CSS", "javascript", "React"],
  },
  {
    id: 3,
    img: "images/r2.jpg",
    name: "Ram prasad sahu",
    stream: "BTech",
    description: "Electronical & Tele Engineer",
    facebook: "https://www.facebook.com/ramprasad.sahu.3551380",
    instagram: "https://instagram.com/sahu.ramaprasad?igshid=MzRlODBiNWFlZA==",
    twitter: "https://www.twitter.com/",
    youtube: "https://www.youtube.com/",
    linkedin: "https://www.linkedin.com/",
    skills: ["Sales", "Marketing", "Strategy", "Intelligence"],
  },
  {
    id: 4,
    img: "images/d.jpg",
    name: "Sabyasachi Nayak",
    stream: "MBA",
    description: "Business Manager",
    facebook: "https://www.facebook.com/sabyasachi.nayak.501",
    instagram: "https://instagram.com/___s_a_b_y_a____?igshid=MzRlODBiNWFlZA==",
    twitter: "https://www.twitter.com/",
    youtube: "https://www.youtube.com/",
    linkedin: "https://www.linkedin.com/",
    skills: ["Sales", "Marketing", "Strategy", "Intelligence"],
  },
  {
    id: 5,
    img: "images/s.jpg",
    name: "Sasanka sekhar subudhi",
    stream: "BTech",
    description: "Civil engineer",
    facebook: "https://www.facebook.com/sekhar.subudhi.716",
    instagram:
      "https://instagram.com/sasanka_sekhar077?igshid=MzRlODBiNWFlZA==    ",
    twitter: "https://www.twitter.com/",
    youtube: "https://www.youtube.com/",
    linkedin: "https://www.linkedin.com/",
    skills: ["Product management", "Teamwork", "Designing", "Creativity"],
  },
];
export default Data;
